#!/bin/bash
make format-check || { echo 'format failed. run "make format" to format your files.' ; exit 1; }
npm run lint || { echo 'linting failed.' ; exit 1;}
npm run test || { echo 'tests failed.' ; exit 1; }

# If tests passed, allow the commit
exit 0